# For more info on HTTP files go to https://aka.ms/vs/httpfile
###
GET http://localhost:5214/blog/1995/06/04

###
GET http://localhost:5214/colors?color=green

###
POST http://localhost:5214/bugReport

